version: "2"

services:
  postgres:
    image: postgres
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - localhost
    volumes:
      - ./var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf

networks:
  localhost: